#include<iostream>
using namespace std;
int main(){


    // logical operator
int a=20;
int b=70;
cout<<(a<b)<<endl;
cout<<(a>b)<<endl;
cout<<(a!=b)<<endl;
cout<<(a==b)<<endl;




// arithmetic operator
    // int a=5;
    // int b=10;

    // cout<<a+b<<endl;
    // cout<<a-b<<endl;
    // cout<<a*b<<endl;
    // cout<<b/a<<endl;
    // cout<<b%a<<endl;



    // cout<<num;
    // int->4 byte
    // int num=50;
    // cout<<num;
    // // cout<<"devendra rahangdale"; cout<<"devender";
    // cout<<endl;
    // cout<<sizeof(num)<<endl;
  
    // //character ->1 byte



    // char ch='k'; 
    //  cout<<sizeof(ch)<<endl;
    // cout<<ch<<endl;


    // float point= 1.76;
    // cout<<point<<endl;
    // cout<<sizeof(point)<<endl;
    // //float->4 byte

    // cout<<endl;

    // // long->4 byte
    // long number=23;
    // cout<<number<<endl;
    // cout<<sizeof(long)<<endl;
}
